/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/FaceAnimationDrago.glb -o src/components/FaceAnimation.jsx 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function FaceAnimation({ ...props }) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/FacewithAnimation.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Face" position={[0, 0, -0.001]} scale={0.01}>
          <group name="root001">
            <primitive object={nodes.pelvis} />
            <group name="Face001">
              <skinnedMesh
                name="Face_1"
                geometry={nodes.Face_1.geometry}
                material={materials["MID_MI_HeadSynthesized_Baked_0.001"]}
                skeleton={nodes.Face_1.skeleton}
                morphTargetDictionary={nodes.Face_1.morphTargetDictionary}
                morphTargetInfluences={nodes.Face_1.morphTargetInfluences}
              />
              <skinnedMesh
                name="Face_2"
                geometry={nodes.Face_2.geometry}
                material={materials["Fbx Default Material 1.001"]}
                skeleton={nodes.Face_2.skeleton}
                morphTargetDictionary={nodes.Face_2.morphTargetDictionary}
                morphTargetInfluences={nodes.Face_2.morphTargetInfluences}
              />
              <skinnedMesh
                name="Face_3"
                geometry={nodes.Face_3.geometry}
                material={materials["Fbx Default Material 2.001"]}
                skeleton={nodes.Face_3.skeleton}
                morphTargetDictionary={nodes.Face_3.morphTargetDictionary}
                morphTargetInfluences={nodes.Face_3.morphTargetInfluences}
              />
              <skinnedMesh
                name="Face_4"
                geometry={nodes.Face_4.geometry}
                material={materials["Fbx Default Material 3.001"]}
                skeleton={nodes.Face_4.skeleton}
                morphTargetDictionary={nodes.Face_4.morphTargetDictionary}
                morphTargetInfluences={nodes.Face_4.morphTargetInfluences}
              />
              <skinnedMesh
                name="Face_5"
                geometry={nodes.Face_5.geometry}
                material={materials["Fbx Default Material 4.001"]}
                skeleton={nodes.Face_5.skeleton}
                morphTargetDictionary={nodes.Face_5.morphTargetDictionary}
                morphTargetInfluences={nodes.Face_5.morphTargetInfluences}
              />
              <skinnedMesh
                name="Face_6"
                geometry={nodes.Face_6.geometry}
                material={materials["Fbx Default Material 5.001"]}
                skeleton={nodes.Face_6.skeleton}
                morphTargetDictionary={nodes.Face_6.morphTargetDictionary}
                morphTargetInfluences={nodes.Face_6.morphTargetInfluences}
              />
              <skinnedMesh
                name="Face_7"
                geometry={nodes.Face_7.geometry}
                material={materials["MID_M_EyelashLowerLODs_Inst_6.001"]}
                skeleton={nodes.Face_7.skeleton}
                morphTargetDictionary={nodes.Face_7.morphTargetDictionary}
                morphTargetInfluences={nodes.Face_7.morphTargetInfluences}
              />
              <skinnedMesh
                name="Face_8"
                geometry={nodes.Face_8.geometry}
                material={materials["Fbx Default Material 7.001"]}
                skeleton={nodes.Face_8.skeleton}
                morphTargetDictionary={nodes.Face_8.morphTargetDictionary}
                morphTargetInfluences={nodes.Face_8.morphTargetInfluences}
              />
              <skinnedMesh
                name="Face_9"
                geometry={nodes.Face_9.geometry}
                material={materials["Fbx Default Material 8.001"]}
                skeleton={nodes.Face_9.skeleton}
                morphTargetDictionary={nodes.Face_9.morphTargetDictionary}
                morphTargetInfluences={nodes.Face_9.morphTargetInfluences}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/FacewithAnimation.glb");
