/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/FullCharactor.glb -o src/components/FullCharactor.jsx 
*/

import React, { forwardRef, useEffect, useRef, useState } from "react";
import { useGraph } from "@react-three/fiber";
import { Html, useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";

const SCRIPT_MAP = {
  Introduction:
    "Hi! I'm Jenny, your assistant. Let's get started. What is your first name?",
  LastName: "Great. Now please tell me your last name.",
  PhoneNumber:
    "Perfect. What is your phone number? Please speak the digits clearly.",
  City: "Thanks. Which city do you currently live in?",
  Pincode:
    "Almost done. What is your pin code? Say it clearly so I can understand.",
  Completion: "All fields have been captured. Would you like to submit now?",
};

const AZURE_TO_GLTF = {
  0: "",
  1: "Viseme_ID-001",
  2: "Viseme_ID-002",
  3: "Viseme_ID-003",
  4: "Viseme_ID-004",
  5: "Viseme_ID-005",
  6: "Viseme_ID-006",
  7: "Viseme_ID-007",
  8: "Viseme_ID-008",
  9: "Viseme_ID-009",
  10: "Viseme_ID-010",
  11: "Viseme_ID-011",
  12: "Viseme_ID-012",
  13: "Viseme_ID-013",
  14: "Viseme_ID-014",
  15: "Viseme_ID-015",
  16: "Viseme_ID-016",
  17: "Viseme_ID-017",
  18: "Viseme_ID-018",
  19: "Viseme_ID-019",
  20: "Viseme_ID-020",
  21: "Viseme_ID-021",
};

export const FullCharactor = forwardRef(
  ({ script, startListening, faceV3CallbackRef, ...props }, ref) => {
    const group = React.useRef();
    const { scene, animations } = useGLTF("/models/FaceCharactorV2.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    const { actions, names } = useAnimations(animations, group);

    const morphMeshesRef = useRef([]);
    const audioRef = useRef(null);
    const visemeTimelineRef = useRef([]);
    const frameRef = useRef(null);

    const promptIndexRef = useRef(0);
    const fetchingRef = useRef(false);
    const animationRunningRef = useRef(false);
    const [started, setStarted] = useState(false);
    const lastScriptRef = useRef(script);

    useEffect(() => {
      const meshes = [];
      clone.traverse((o) => {
        if (o.isMesh && o.morphTargetDictionary) {
          o.morphTargetInfluences.fill(0);
          meshes.push(o);
        }
      });
      morphMeshesRef.current = meshes;

      // ⏳ wait 10 seconds, then hide loader
      const timer = setTimeout(() => {
        props.setShowLoader(false);
      }, 5000);

      return () => clearTimeout(timer);
    }, [clone]);

    useEffect(() => {
      if (!animations) return;
      animations.forEach((clip) => {
        clip.tracks = clip.tracks.filter(
          (t) =>
            !t.name.includes("morphTargetInfluences") &&
            !t.name.toLowerCase().includes("face")
        );
      });
    }, [animations]);

    useEffect(() => {
      if (!actions || !names.length) return;
      const action = actions[names[0]];
      if (!action) return;
      action.reset();
      action.time = 0.5;
      action.fadeIn(0.5).play();
    }, [actions, names]);

    function hardReset() {
      morphMeshesRef.current.forEach((m) => {
        if (m.morphTargetInfluences) {
          m.morphTargetInfluences.fill(0);
        }
      });
    }

    function smoothResetAll() {
      animationRunningRef.current = false;
      if (frameRef.current) cancelAnimationFrame(frameRef.current);

      let t = 0;
      function animate() {
        t += 0.06;

        morphMeshesRef.current.forEach((mesh) => {
          const infl = mesh.morphTargetInfluences;
          if (!infl) return;
          for (let i = 0; i < infl.length; i++) {
            infl[i] = THREE.MathUtils.lerp(infl[i], 0, 0.25);
          }
        });

        if (t < 1) requestAnimationFrame(animate);
      }
      animate();
    }
    function startVisemeAnimation() {
      if (!audioRef.current) return;
      animationRunningRef.current = true;

      const FADE_IN = 120;
      const FADE_OUT = 180;
      const MAX_STRENGTH = 0.5;
      const DECAY = 0.12;

      function animate() {
        if (!animationRunningRef.current || !audioRef.current) return;

        const now = audioRef.current.currentTime * 1000;

        morphMeshesRef.current.forEach((mesh) => {
          const dict = mesh.morphTargetDictionary;
          const infl = mesh.morphTargetInfluences;
          if (!dict || !infl) return;

          // Smooth decay (prevents mouth sticking)
          for (let i = 0; i < infl.length; i++) {
            infl[i] = THREE.MathUtils.lerp(infl[i], 0, DECAY);
          }

          for (const v of visemeTimelineRef.current) {
            const t = now - v.offset_ms;

            // Skip visemes out of range
            if (t < -FADE_IN || t > v.duration_ms + FADE_OUT) continue;

            let s = 0;

            // Fade in
            if (t >= 0 && t <= FADE_IN) {
              s = THREE.MathUtils.smoothstep(t / FADE_IN, 0, 1);
            }
            // Hold
            else if (t > FADE_IN && t < v.duration_ms) {
              s = 1;
            }
            // Fade out
            else if (t >= v.duration_ms) {
              s =
                1 -
                THREE.MathUtils.smoothstep(
                  (t - v.duration_ms) / FADE_OUT,
                  0,
                  1
                );
            }

            const idx = dict[v.viseme_name];
            if (idx !== undefined) {
              infl[idx] = Math.max(infl[idx], s * MAX_STRENGTH);
            }
          }
        });

        frameRef.current = requestAnimationFrame(animate);
      }

      animate();
    }

    function forceStopAudioAndAnimation() {
      animationRunningRef.current = false;
      if (frameRef.current) cancelAnimationFrame(frameRef.current);
      if (audioRef.current) {
        try {
          audioRef.current.pause();
          audioRef.current.currentTime = 0;
        } catch {}
      }
    }

    async function fetchVisemeData(text) {
      props.setIsLoading(true);
      if (fetchingRef.current) return;
      fetchingRef.current = true;

      try {
        const res = await fetch(
          `http://127.0.0.1:8000/api/generate-viseme/?text=${encodeURIComponent(
            text
          )}`
        );

        const data = await res.json();
        const raw = data.visemes || [];

        // Build viseme timeline with computed durations
        visemeTimelineRef.current = raw.map((v, i) => {
          const next = raw[i + 1];
          return {
            viseme_id: v.viseme_id,
            viseme_name: AZURE_TO_GLTF[v.viseme_id], // <— IMPORTANT
            offset_ms: v.offset_ms,
            duration_ms: next ? next.offset_ms - v.offset_ms : 120,
          };
        });

        // Decode base64 audio
        const bytes = Uint8Array.from(atob(data.audio_file_base64), (c) =>
          c.charCodeAt(0)
        );
        const audioURL = URL.createObjectURL(
          new Blob([bytes], { type: data.mime_type || "audio/mpeg" })
        );

        forceStopAudioAndAnimation();

        const audio = new Audio(audioURL);
        audioRef.current = audio;

        // When audio finishes
        audio.onended = () => {
          animationRunningRef.current = false;

          // FIX: Force mouth close fully
          hardReset();
          smoothResetAll();

          fetchingRef.current = false;

          setTimeout(() => {
            if (typeof startListening === "function") startListening();
          }, 400);

          if (faceV3CallbackRef?.current) faceV3CallbackRef.current();
        };

        // Start animation + audio
        startVisemeAnimation();
        audio.play();
      } catch (err) {
        console.error("Viseme fetch error:", err);
        fetchingRef.current = false;
      }
    }

    function playNextPrompt() {
      const text = SCRIPT_MAP[script];
      if (!text) return;

      if (promptIndexRef.current >= 1) return;
      promptIndexRef.current = 1;

      fetchVisemeData(text);
    }

    function handleStart() {
      promptIndexRef.current = 0;
      hardReset();
      setStarted(true);

      setTimeout(() => playNextPrompt(), 400);
    }

    useEffect(() => {
      if (!started) return;
      if (script === lastScriptRef.current) return;

      lastScriptRef.current = script;

      promptIndexRef.current = 0;
      forceStopAudioAndAnimation();
      fetchingRef.current = false;

      setTimeout(() => playNextPrompt(), 250);
    }, [script, started]);

    useEffect(() => {
      return () => {
        animationRunningRef.current = false;
        if (frameRef.current) cancelAnimationFrame(frameRef.current);
        if (audioRef.current) {
          try {
            audioRef.current.pause();
            audioRef.current.src = "";
          } catch {}
        }
      };
    }, []);
    useEffect(() => {
      clone.position.set(0, 0, 0);
      clone.rotation.set(0, 0, 0);
      clone.scale.set(1, 1, 1);
      clone.updateMatrixWorld(true);
    }, [clone]);

    return (
      <group ref={group} {...props} dispose={null} scale={6}>
        {!started && (
          <Html fullscreen className="pointer-events-auto">
            <div className="w-full h-full flex items-end justify-center pb-10">
              <div
                onClick={handleStart}
                className="cursor-pointer px-6 py-3 text-lg md:text-xl rounded-lg 
            bg-black/60 text-white border border-white/40 
            backdrop-blur-sm hover:bg-black/80 transition-all"
              >
                Click to Begin
              </div>
            </div>
          </Html>
        )}

        <group scale={35} position={[0, -42, 0]}>
          <primitive object={clone} />
        </group>
      </group>
    );
  }
);
export default FullCharactor;
useGLTF.preload("/models/FaceCharactorV2.glb");
